# Generated by Django 4.1.6 on 2023-02-12 16:35

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Result Name')),
                ('inputs', picklefield.fields.PickledObjectField(editable=False)),
                ('outputs', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
