# Generated by Django 4.2.7 on 2023-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_data_remove_result_inputs_remove_result_outputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='type',
        ),
        migrations.AddField(
            model_name='data',
            name='field_type',
            field=models.CharField(choices=[('power', 'Power (kWh)'), ('time', 'Time (h/24)'), ('lamps', 'Lamps (count)'), ('lamps_unit_price', 'Unite Price (for lamps)'), ('energy_consumed', 'Consumed Energy'), ('cost', 'Cost (₺)')], default='null_title', max_length=200, verbose_name='Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=20, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='data',
            name='lighting_type',
            field=models.CharField(choices=[('advanced', 'Advanced'), ('standard', 'Standart')], max_length=200, verbose_name='Ligthing Type'),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
    ]
